spring:
  datasource:
    url: jdbc:postgresql://postgres-db/prm392
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  application:
    name: users
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437