services:
  postgres-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: prm392
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9082:5432"
    volumes:
      - ./postgres-db/init.sql:/docker-entrypoint-initdb.d/init.sql
  prm392-service:
    build:
      context: ../dotnet/src
      dockerfile: Dockerfile
    container_name: prm392-service
    ports:
      - "9080:8080"
      - "9081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres-db;Database=prm392;Username=postgres;Password=postgres"
  prm392-auth:
    build:
      context: ../users
      dockerfile: Dockerfile
    container_name: prm392-auth
    ports:
      - "9084:8080"